services:
  app:
    entrypoint:
    - sleep
    - infinity
    image: ubuntu/dotnet-aspnet:7.0-23.04_42
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock

